name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.14.0
        coq-version:
          - 8.14.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam install ocamlformat.0.22.4
      - run: opam exec -- make fmt-check
      - run: opam pin add coq ${{ matrix.coq-version }}
      - run: opam pin add coq-of-ocaml.dev . --no-action
      - run: opam depext conf-ruby --yes
      - run: opam install coq-of-ocaml --deps-only
      - run: opam install coq-of-ocaml --verbose
      - run: opam exec -- make coverage
      - run: opam exec -- bisect-ppx-report send-to Codecov
